// English case data, mirrors lib/cases.ts structure. Selected when locale === 'en'.
import type { CaseDetail } from './cases';

export const HEX_AXES_EN = ['Hospital', 'Accident', 'Crit. illness', 'Life', 'TPD', 'LTC'] as const;

export const DISCLAIMERS_EN: string[] = [
  'This page is an anonymised summary of a real client plan; all identifying details and specific product names are removed, and sums and premiums are illustrative / for reference, solely to explain the planning approach.',
  'The figures are organised for illustration and do not represent guaranteed returns; dividends, cash-value growth and similar are non-guaranteed and depend on the insurer’s actual performance.',
  'Actual contributions, payouts and coverage amounts are subject to the insurer’s official policy documents.',
  'A plan that suits the client in a case may not suit you. Any arrangement should be decided after a full needs analysis, based on your personal circumstances.',
  'This case follows MAS MoneySense basic financial-planning principles, protect first, grow later, live within your means.',
];

export const CASES_EN: CaseDetail[] = [
  // 1. 25 first job
  {
    slug: 'first-job',
    age: 25,
    gender: 'male',
    mapLabel: 'Age 25 · New to Singapore',
    stageIcon: 'family',
    theme: 'Laying the protection foundation',
    icon: 'seedling',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · New to work · Building the foundation',
    title: 'New to work with a tight budget, how should the first cover be built?',
    titleHi: 'how should the first cover be built?',
    lead: 'Good income but thin savings, his biggest fear is "one illness or accident throwing everything off track." He doesn’t need complex products, just to secure the basics on no more than 15% of income, exactly what MoneySense recommends at this age.',
    pills: ['EP holder', 'Big tech', 'Income ~S$60,000/yr', 'Single, no dependants', 'Emergency fund first'],
    hexBefore: [0, 0, 0, 0, 0, 0],
    hexAfter: [3, 3, 2, 0, 0, 0],
    hexBeforeLabel: 'Before · almost unprotected',
    hexAfterLabel: 'After · three corners lit',
    hexNote:
      'At 25, single, with no dependants and no debt, Life / TPD / long-term care are left for later, not because they don’t matter, but because the need hasn’t arisen. They fill in stage by stage: Life when buying a home, Life/TPD topped up when starting a family, long-term care later in life. That’s how the hexagon fills in, one corner at a time.',
    profile: [
      { icon: '💼', title: 'Assets today', items: ['Just over a year into work, modest savings', 'Building a 3–6 month emergency fund', 'No property, car or loans'] },
      { icon: '😟', title: 'His worries', items: ['Company group medical lapses once he leaves', 'Knows little about insurance, wary of being sold to', 'Doesn’t want premiums eating his cash flow'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Company group medical (basic) ✓', 'Personal policies, none ✕'] },
      { icon: '🎯', title: 'Core needs', items: ['Cover the health / accident baseline on a limited budget', 'A foundation that follows him and lasts for life', 'Keep premiums off his cash flow'] },
    ],
    analysisTitle: 'At this stage, the smartest "investment" is health',
    analysis: [
      'MoneySense is clear for ages 19–29: build an emergency fund first, then put no more than 15% of income toward protection.',
      'The best "investment" now is to lock in health cover while young, at low rates, rather than rushing into savings or investment products.',
    ],
    quote: 'What he lacks isn’t returns, it’s the floor that keeps one accident from derailing a career that’s just begun.',
    solutionEyebrow: '03 / Solution · A 3-part protection set (anonymised real plan)',
    solutionTitle: 'Accident + hospital + critical illness, all at once',
    solutionLead: 'No savings or investment products, just three basic, best-value layers as a first safety net: personal accident, private hospital, and multi-claim critical illness. The sums and premiums below are an anonymised illustration from a real client plan.',
    meta: [
      { label: '① Personal accident', value: 'S$210 / yr', sub: 'Accidental death S$500k + medical' },
      { label: '② Private hospital plan', value: 'S$1,510 / yr', sub: 'Up to S$2M/yr · incl. cancer rider' },
      { label: '③ Multi-claim critical illness', value: 'S$1,478 / yr', sub: 'S$200k on diagnosis · to age 65' },
      { label: 'Three plans total', value: 'S$3,198 / yr', sub: '~S$266/mo · incl. 9% GST' },
    ],
    table: {
      head: ['Cover', 'Sum (illustrative)', 'Annual premium'],
      rows: [
        ['Personal accident', 'Accidental death S$500k + fractures / medical', 'S$210'],
        ['Private hospital', 'Up to S$2M/yr · premium won’t rise after a claim', 'S$1,510'],
        ['Multi-claim CI', 'S$200k on diagnosis · multiple claims · to 65', 'S$1,478'],
        ['Total', '~S$266 / month (incl. 9% GST)', 'S$3,198 / yr'],
      ],
    },
    plans: [
      {
        no: 'PLAN 01 · Personal accident',
        name: 'All-round cover for accidents',
        tagline: 'Knocks, fractures, hospital stays, even a phone or gym pass',
        price: 'S$210 / yr',
        sumLabel: 'Accidental death',
        sum: 'S$500k',
        benefits: [
          { b: 'Accidental death S$500k', s: 'Covered wherever in the world an accident happens' },
          { b: 'Fractures / dislocations + medical', s: 'Medical bills, fractures and dislocations reimbursed' },
          { b: 'Even a damaged phone or laptop', s: 'Electronics damaged during a hospital stay can be compensated' },
          { b: 'Gym pass · event tickets not wasted', s: 'Missed gym memberships or show tickets can be compensated' },
        ],
      },
      {
        no: 'PLAN 02 · Private hospital plan',
        name: 'Fall ill and still afford private care',
        tagline: 'Choose your private ward, big bills covered, premium won’t rise after a claim',
        price: 'S$1,510 / yr',
        sumLabel: 'Annual hospital limit',
        sum: 'S$2M',
        benefits: [
          { b: 'A private hospital ward', s: 'Upgrade to any standard private-hospital ward for a smoother stay' },
          { b: 'Up to S$2M a year', s: 'Big bills covered, with no lifetime aggregate limit' },
          { b: 'You pay only a small share', s: 'After the deductible, just 5% co-pay, capped at S$6,000/yr' },
          { b: 'Premium stays the same after a claim', s: 'Even if you claim this year, next year’s premium won’t rise for it' },
          { b: 'Added cancer cover', s: 'Extra cover for cancer outpatient drugs, for calmer treatment choices' },
        ],
      },
      {
        no: 'PLAN 03 · Multi-claim critical illness',
        name: 'When illness strikes, claim again and again',
        tagline: 'A cash sum steadies lost income; recover in peace, and claim again',
        price: 'S$1,478 / yr',
        sumLabel: 'CI on diagnosis',
        sum: 'S$200k',
        benefits: [
          { b: 'S$200k cash on diagnosis', s: 'Spend it your way, replace income, pay the mortgage, recover well' },
          { b: 'Claim many times', s: 'Unlimited claims for severe-stage illnesses; cover resets each year' },
          { b: 'Relapses covered too', s: 'Cancer, stroke or heart attack recurring can be claimed again' },
          { b: 'Premiums waived after illness', s: 'After an early-stage diagnosis, the insurer pays future premiums' },
          { b: 'Covers 150 early / intermediate / severe conditions', s: 'From early detection to severe stage, covered to age 65' },
        ],
      },
    ],
    dataChips: [
      { label: 'Premium vs income', value: '~5% · income S$60,000/yr' },
      { label: 'Three risks', value: 'Accident · hospital · CI, all set' },
      { label: 'Cost', value: '~S$266/mo · under S$9/day' },
    ],
  },

  // 2. 30 new home
  {
    slug: 'new-home',
    age: 30,
    gender: 'female',
    mapLabel: 'Age 30 · Buying a home',
    stageIcon: 'home',
    theme: 'Protecting the home and each other',
    icon: 'home',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · Buying a home · Protecting home & each other',
    title: 'Just took on a mortgage, if I’m the one who falls, can we keep the home?',
    titleHi: 'can we keep the home?',
    lead: 'The foundation was laid back at 25, but buying a home raises the stakes, the gap is now in "family responsibility." She doesn’t need more insurance, just a precise hedge against the mortgage risk.',
    pills: ['PR + citizen household', 'Dual income', 'S$600k mortgage', 'Steady, conservative'],
    hexBefore: [3, 3, 2, 0, 0, 0],
    hexAfter: [3, 3, 3, 3, 1, 0],
    hexBeforeLabel: 'Before buying · three corners',
    hexAfterLabel: 'After · Life added',
    hexNote:
      'This stage adds the key piece, Life. A 30-year level term life policy (premiums locked) covers the mortgage years, with the couple naming each other as beneficiary; critical illness is topped up at the same time. TPD can ride on the life policy; long-term care waits for a later stage.',
    profile: [
      { icon: '🏠', title: 'Assets today', items: ['Just bought their own home', 'Mortgage ~S$60****', 'Stable dual-income cash flow; savings used on the down payment'] },
      { icon: '😟', title: 'Her worries', items: ['"If one of us loses our income, can the other carry the whole mortgage?"'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Hospital ✓ · Accident ✓', 'Critical illness ◐ (low)', 'Life ✕'] },
      { icon: '🎯', title: 'Core needs', items: ['If one dies / falls ill, the mortgage won’t crush the other', 'Close the critical-illness gap'] },
    ],
    analysisTitle: 'The biggest exposure is that mortgage',
    analysis: [
      'MoneySense rule of thumb: death / TPD cover ~9× annual income, critical illness ~4× annual income.',
      'Their biggest exposure is the mortgage, a fixed, long-term debt best covered precisely with a 30-year level term life policy (premiums locked). Total premiums still stay within 15% of household income.',
    ],
    quote: 'She doesn’t want more insurance, she wants the home to stay safe, no matter what.',
    solutionEyebrow: '03 / Solution · Mutual term life for the couple (anonymised real plan)',
    solutionTitle: 'One 30-year term policy each, naming the other',
    solutionLead: 'Each takes a 30-year term life policy naming the other as beneficiary: the term covers the mortgage years, premiums are locked for 30 years from year one, and death / TPD / critical illness / early CI are all addressed. Below is an anonymised illustration from a real client plan.',
    meta: [
      { label: 'His policy', value: 'S$2,857 / yr', sub: 'Death + TPD S$1M · CI S$1M' },
      { label: 'Her policy', value: 'S$2,302 / yr', sub: 'Death + TPD S$1M · CI S$500k' },
      { label: 'Household total', value: 'S$5,159 / yr', sub: '~S$430/mo · locked 30 yrs' },
      { label: 'Term', value: '30 years', sub: 'Covers the mortgage years' },
    ],
    table: {
      head: ['Cover (illustrative)', 'Him', 'Her'],
      rows: [
        ['Death / terminal illness', 'S$1,000,000', 'S$1,000,000'],
        ['TPD', 'S$1,000,000', 'S$1,000,000'],
        ['Critical illness', 'S$1,000,000', 'S$500,000'],
        ['Early CI', 'S$200,000', 'S$200,000'],
        ['Annual premium', 'S$2,857', 'S$2,302'],
      ],
    },
    dataChips: [
      { label: 'Beneficiary', value: 'Each other' },
      { label: 'Premium', value: 'Locked 30 yrs · ~S$430/mo' },
      { label: 'Type', value: 'Term life · no cash value' },
    ],
  },

  // 3. 32 new parents
  {
    slug: 'new-parents',
    age: 32,
    gender: 'female',
    mapLabel: 'Age 32 · Children’s education',
    stageIcon: 'education',
    theme: 'Cover and a future for the child',
    icon: 'baby',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · New parents · Cover & education fund',
    title: 'Baby’s just arrived, where do cover and the education fund begin?',
    titleHi: 'where do cover and the education fund begin?',
    lead: 'Many new parents instinctively "insure the child first," but MoneySense puts the order differently, parents are the child’s biggest "policy." We shore up the parents first, then build the child’s foundation and start saving for the future.',
    pills: ['Newborn', 'Dual-income family', 'Parents first', 'Education fund started'],
    hexBefore: [3, 3, 3, 3, 1, 0],
    hexAfter: [3, 3, 3, 3, 3, 0],
    hexBeforeLabel: 'Before the baby',
    hexAfterLabel: 'After · TPD completed',
    hexNote:
      'A new baby raises family responsibility again, so the parents’ Life and TPD are topped up (TPD completed). The child gets their own "small hexagon": child hospital + child accident + (optional) child critical illness. The education fund starts as a "future cash flow" at the same time.',
    profile: [
      { icon: '👶', title: 'Family today', items: ['Baby just born', 'Spending pattern is shifting', 'Starting to worry about future education costs'] },
      { icon: '😟', title: 'Her worries', items: ['Wants the best for the child but unsure of the order', 'Worried the education fund won’t be enough when needed'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Parents: hospital / accident / CI in place ✓', 'Child: no policies yet ✕'] },
      { icon: '🎯', title: 'Core needs', items: ['Basic health cover for the baby', 'Long-term saving for education around age 18'] },
    ],
    analysisTitle: 'Parents first, then the child, don’t reverse the order',
    analysis: [
      'Newborn cover rewards starting early: the sooner it’s set up, the simpler the underwriting and the lower the rate.',
      'But order matters, parents first, child second. The parents’ income is the family’s cash-flow engine; the parents are the child’s biggest "policy."',
    ],
    quote: 'The child’s cover matters, but make sure the parents are solid first.',
    solutionEyebrow: '03 / Solution · Two steps',
    solutionTitle: 'Lay the baby’s foundation, then save for the future',
    solutionLead: 'Step one secures the baby’s basic health; step two builds long-term savings for education around age 18.',
    meta: [
      { label: '① Child hospital plan', value: '~S$2**', sub: 'Health foundation' },
      { label: '② Child accident', value: '~S$2**', sub: 'A must for active years' },
      { label: '③ (Optional) child CI', value: 'Locks S$10****', sub: 'Low lifetime rate' },
      { label: '④ Education savings', value: '~S$2***/yr', sub: 'Cash flow when it’s needed' },
    ],
    table: {
      head: ['Who', 'Dimension', 'After'],
      rows: [
        ['Parents', 'Life / TPD', '✅ Heavier duty · topped up'],
        ['Child', 'Hospital / Accident', '✅ Health foundation'],
        ['Child', 'CI (optional)', '◐ Lock rate early'],
        ['Future', 'Education fund', '✅ Long-term saving started'],
      ],
    },
    dataChips: [
      { label: 'Key reminder', value: 'Parents are the child’s biggest policy' },
      { label: 'Added for child', value: 'Hospital · Accident · (CI optional)' },
      { label: 'Education fund start', value: 'From birth' },
    ],
  },

  // 4. 35 wealth growth
  {
    slug: 'wealth-growth',
    age: 35,
    gender: 'female',
    mapLabel: 'Age 35 · Wealth growth',
    stageIcon: 'wealth',
    theme: 'Tax, growth, early retirement',
    icon: 'growth',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · Wealth growth · Tax & early retirement',
    title: 'Thinking at 35 about life at 50, how to save tax, grow wealth, and retire early?',
    titleHi: 'save tax, grow wealth, and retire early?',
    lead: 'Her protection hexagon was completed long ago; now she wants to put the "pre-tax" part of a high income to work, first maxing SRS to cut tax, then using a "grow-first, dividends-later" pool to lay steady cash flow toward early retirement at 50.',
    pills: ['EP holder', 'Family-business heir', 'Target: retire at 50', 'Max SRS tax relief'],
    hexBefore: [3, 3, 3, 3, 3, 0],
    hexAfter: [3, 3, 3, 3, 3, 1],
    hexBeforeLabel: 'Protection layer full',
    hexAfterLabel: 'Into growth + retirement',
    hexNote:
      'The protection layer is already full, so this stage adds no more cover and shifts the focus to "growth + retirement." The assets move from "all protection" to "protection base + tax optimisation + retirement cash flow."',
    profile: [
      { icon: '💰', title: 'Assets today', items: ['High income, complete cover', 'Ongoing investable surplus', 'No systematic tax planning yet'] },
      { icon: '😟', title: 'Her worries', items: ['Tax burden is on the high side', 'Wants to retire at 50 but has no clear cash-flow path', 'Doesn’t want to watch the markets'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Hospital / accident / CI ✓', 'Life / TPD ✓', 'Protection layer full'] },
      { icon: '🎯', title: 'Core needs', items: ['Legal tax saving', 'Steady growth on spare cash', 'A supplementary cash flow for retiring at 50'] },
    ],
    analysisTitle: 'SRS: one of the few direct tax cuts for high-income EPs',
    analysis: [
      'For a high-income EP holder, SRS (Supplementary Retirement Scheme) is one of the few tools that directly reduces tax: foreigners can contribute up to S$35,700 a year, cutting that year’s taxable income.',
      'But SRS cash sitting idle does little, pair it with a "grow-first, dividends-later" strategy so the money compounds over the 15 years from 35 to 50, then converts into a dividend cash flow in retirement.',
    ],
    quote: 'The confidence to retire early comes from certain cash flow, not from betting on returns.',
    solutionEyebrow: '03 / Solution · Tax + growth + retirement, all three',
    solutionTitle: 'Set up at 35 → grow for 15 years → draw from 50',
    solutionLead: 'Use SRS to cut tax this year, a "grow-first, dividends-later" fund to compound long-term, and steady savings to supplement retirement cash flow.',
    meta: [
      { label: '① Max SRS', value: 'S$35,700/yr', sub: 'Directly offsets taxable income' },
      { label: '② Grow-then-dividend fund', value: '~S$****/yr', sub: 'Grow early · dividends later' },
      { label: '③ Steady savings plan', value: 'Draw from 50', sub: 'Supplements retirement cash flow' },
    ],
    table: {
      head: ['Stage', 'Action', 'Goal'],
      rows: [
        ['Age 35', 'Max SRS + set up fund', 'Cut tax now · start compounding'],
        ['35→50', 'Grow', 'Let the principal compound over 15 years'],
        ['From 50', 'Switch to dividends / draw', 'Supplementary cash flow for early retirement'],
      ],
    },
    dataChips: [
      { label: 'Annual tax relief', value: 'SRS S$35,700' },
      { label: 'Timeline', value: '35 → 50 (15 years)' },
      { label: 'Retirement strategy', value: 'Grow first, dividends later' },
    ],
  },

  // 5. 40 USD retirement
  {
    slug: 'usd-retirement',
    age: 40,
    gender: 'male',
    mapLabel: 'Age 40 · Retirement planning',
    stageIcon: 'retire',
    theme: 'Steady USD retirement cash flow',
    icon: 'stable',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · Retirement planning · USD savings plan',
    title: 'Solid income, how should retirement cash flow and USD savings be designed?',
    titleHi: 'retirement cash flow and USD savings be designed?',
    lead: 'He isn’t chasing returns, he wants a steady, flexible, inheritable home for some idle USD: certainty, plus the option to start early if his career rhythm changes.',
    pills: ['Senior executive', 'US$500k idle USD', 'Low risk', 'Flexible either way'],
    hexBefore: [3, 3, 3, 3, 3, 1],
    hexAfter: [3, 3, 3, 3, 3, 2],
    hexBeforeLabel: 'Fully protected',
    hexAfterLabel: 'Add retirement cash flow + early LTC',
    hexNote:
      'Protection is complete; this stage adds the early shape of "retirement cash flow" and "long-term care." The assets begin shifting from "protection + growth" toward "cash flow + legacy."',
    profile: [
      { icon: '💵', title: 'Assets today', items: ['Stable career, peak earnings', 'US$50**** of USD not needed short-term'] },
      { icon: '😟', title: 'His considerations', items: ['No appetite for short-term volatility', 'Worried there’s nothing ready to start if his career rhythm changes'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Group medical, basic hospital ✓', 'Some life / CI, basic accident ✓'] },
      { icon: '🎯', title: 'Core needs', items: ['Long-term steady cash flow', 'Steady + flexible', 'Considers family legacy too'] },
    ],
    analysisTitle: 'A flexible home for some idle USD',
    analysis: [
      'The need is clear: not chasing returns, but a steady home for idle USD, flexible either way, and inheritable.',
      'What fits him best is "flexible either way": start early if needed, keep compounding if not.',
    ],
    quote: 'He wants certainty, and the ease of money he can use anytime, and pass on if he doesn’t.',
    solutionEyebrow: '03 / Solution · USD savings plan (single premium)',
    solutionTitle: 'Pay once, draw at your own pace',
    solutionLead: 'A single premium; choose to draw annual cash flow from year 5 or year 15, covered to age 100, with any unused portion passed on.',
    meta: [
      { label: 'Single premium', value: 'US$50****', sub: 'Pay only once' },
      { label: 'Early draw (from yr 5)', value: '~US$2****/yr', sub: 'Can start early' },
      { label: 'Later draw (from yr 15)', value: '~US$4****/yr', sub: 'Compounds longer' },
      { label: 'Coverage', value: 'To age 100', sub: 'Unused keeps compounding · inheritable' },
    ],
    table: {
      head: ['Draw option', 'Start', 'Annual cash flow (illustrative)'],
      rows: [
        ['Early', 'From year 5', '~US$2****'],
        ['Later', 'From year 15', '~US$4****'],
      ],
    },
    dataChips: [
      { label: 'Funding', value: 'Single premium' },
      { label: 'Draw flexibility', value: 'Year 5 / 15 optional' },
      { label: 'Coverage', value: 'To age 100 + legacy' },
    ],
  },

  // 6. 45 business owner
  {
    slug: 'business-owner',
    age: 45,
    gender: 'male',
    mapLabel: 'Age 45 · Growing a business',
    stageIcon: 'business',
    theme: 'Offence and defence · a complete hexagon',
    icon: 'building',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · Business owner · Growth / floor / legacy',
    title: 'Company and family money are mixed, how to grow, protect the floor, and pass it on?',
    titleHi: 'grow, protect the floor, and pass it on?',
    lead: 'As the founder of a tech company, his risks differ from an ordinary executive’s, business swings, and blurred lines between personal and company assets. A combined approach fills in the hexagon’s last corner while arranging growth, a safety floor and legacy all at once.',
    pills: ['Tech company founder', 'Family + business duty', 'Asset segregation', 'High-leverage legacy'],
    hexBefore: [3, 3, 3, 3, 3, 2],
    hexAfter: [3, 3, 3, 3, 3, 3],
    hexBeforeLabel: 'Almost complete',
    hexAfterLabel: 'Hexagon fully closed ⭐',
    hexNote:
      'From a single corner at 25 to here at 45, the hexagon closes completely: long-term care is filled in, Life is boosted with high leverage via IUL, and a layer of business asset segregation and legacy is added on top.',
    profile: [
      { icon: '🏢', title: 'Assets today', items: ['Runs a tech company, with meaningful savings', 'Blurred line between personal and company assets'] },
      { icon: '😟', title: 'His considerations', items: ['Business swings, fears "company trouble dragging in the family"', 'Wants to leave the family a certain sum'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Health cover complete (hospital / CI / accident) ✓', 'Some life cover, but a gap remains against the dual duty'] },
      { icon: '🎯', title: 'Core needs', items: ['Part of the money to outpace inflation long-term', 'Part as a high-leverage death-benefit floor', 'Asset segregation + legacy'] },
    ],
    analysisTitle: 'Why a "combination," not a single product',
    analysis: [
      'A participating fund provides "steadiness," and IUL provides "protection + flexible growth", exactly matching his "offence and defence" needs.',
      'Unique to owners: use a policy structure to segregate and pass on personal vs. company assets, so business swings don’t breach the family’s floor.',
    ],
    quote: 'Keep the company’s swings from breaching the family’s floor.',
    solutionEyebrow: '03 / Solution · A combination',
    solutionTitle: 'Participating / growth fund + indexed universal life',
    solutionLead: 'One combination: a participating / growth fund for retirement cash flow (two ways to draw), plus indexed universal life to leverage a high death benefit and legacy.',
    meta: [
      { label: '① Participating / growth fund', value: 'S$100k/yr × 5', sub: 'Retirement income · two options (below)' },
      { label: '② Indexed universal life (IUL)', value: 'US$3M cover', sub: 'Single premium US$371k · ~8× · legacy' },
    ],
    table: {
      head: ['Tool', 'Role', 'Notes'],
      rows: [
        ['Participating fund', 'Steady base', 'Smoothed growth · for mid/long-term money'],
        ['IUL', 'Protection + flexible growth', 'Leverages ~US$1***** cover · cash value with a floor'],
        ['Asset segregation', 'Owner-specific', 'Clear lines · a certain sum set aside for family'],
      ],
    },
    plans: [
      {
        no: 'Core tool · Indexed universal life (IUL)',
        name: 'High-leverage death benefit + index-linked cash-value growth',
        tagline: 'One single premium leverages several times the death benefit; cash value tracks the index, with a floor in down years and a cap in up years',
        price: 'Single premium US$370,962',
        sumLabel: 'Death benefit',
        sum: 'US$3M',
        benefits: [
          { b: 'Death benefit ~US$3M', s: 'A single premium of ~US$371k leverages ~8× death benefit for the family' },
          { b: 'Cash value tracks the S&P 500', s: '100% of net premium goes to the index account to share long-term US equity upside' },
          { b: 'Floor 0% · cap 9%', s: 'In down years the cash value doesn’t fall (0% floor); upside is capped at 9%' },
          { b: 'Guaranteed fixed-account base', s: '4.30% guaranteed for the first 3 years, then 2.00% (guaranteed rate)' },
          { b: 'Special bonus 0.35% from year 11', s: 'Paid from policy year 11 to age 100 (non-guaranteed)' },
          { b: 'Illustrated long-term ~4% (non-guaranteed)', s: 'Illustrated yield on surrender at 85 ~4.04%; actuals depend on index performance and charges' },
        ],
      },
    ],
    dataChips: [
      { label: 'Death-benefit leverage', value: 'US$3M · ~8×' },
      { label: 'Protection hexagon', value: 'Fully closed' },
      { label: 'Return nature', value: 'Dividends & cash value non-guaranteed · per policy' },
    ],
  },
];
