// English case data — mirrors lib/cases.ts structure. Selected when locale === 'en'.
import type { CaseDetail } from './cases';

export const HEX_AXES_EN = ['Hospital', 'Accident', 'Crit. illness', 'Life', 'TPD', 'LTC'] as const;

export const DISCLAIMERS_EN: string[] = [
  'This page is an anonymised summary of a real client situation; all identifying details are removed and amounts are shown as placeholders / illustrative, solely to explain the planning approach.',
  'The figures are organised for illustration and do not represent guaranteed returns; dividends, cash-value growth and similar are non-guaranteed and depend on the insurer’s actual performance.',
  'Actual contributions, payouts and coverage amounts are subject to the insurer’s official policy documents.',
  'A plan that suits the client in a case may not suit you. Any arrangement should be decided after a full needs analysis, based on your personal circumstances.',
  'This case follows MAS MoneySense basic financial-planning principles — protect first, grow later, live within your means.',
];

export const CASES_EN: CaseDetail[] = [
  // 1. 25 first job
  {
    slug: 'first-job',
    age: 25,
    gender: 'male',
    mapLabel: 'Age 25 · New to Singapore',
    stageIcon: 'family',
    theme: 'Laying the protection foundation',
    icon: 'seedling',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · New to work · Building the foundation',
    title: 'New to work with a tight budget — how should the first cover be built?',
    titleHi: 'how should the first cover be built?',
    lead: 'Good income but thin savings — his biggest fear is "one illness or accident throwing everything off track." He doesn’t need complex products, just to secure the basics on no more than 15% of income — exactly what MoneySense recommends at this age.',
    pills: ['EP holder', 'Big tech', 'Single, no dependants', 'Emergency fund first'],
    hexBefore: [0, 0, 0, 0, 0, 0],
    hexAfter: [3, 3, 2, 0, 0, 0],
    hexBeforeLabel: 'Before · almost unprotected',
    hexAfterLabel: 'After · three corners lit',
    hexNote:
      'At 25, single, with no dependants and no debt, Life / TPD / long-term care are left for later — not because they don’t matter, but because the need hasn’t arisen. They fill in stage by stage: Life when buying a home, Life/TPD topped up when starting a family, long-term care later in life. That’s how the hexagon fills in, one corner at a time.',
    profile: [
      { icon: '💼', title: 'Assets today', items: ['Just over a year into work, modest savings', 'Building a 3–6 month emergency fund', 'No property, car or loans'] },
      { icon: '😟', title: 'His worries', items: ['Company group medical lapses once he leaves', 'Knows little about insurance, wary of being sold to', 'Doesn’t want premiums eating his cash flow'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Company group medical (basic) ✓', 'Personal policies — none ✕'] },
      { icon: '🎯', title: 'Core needs', items: ['Cover the health / accident baseline on a limited budget', 'A foundation that follows him and lasts for life', 'Keep premiums off his cash flow'] },
    ],
    analysisTitle: 'At this stage, the smartest "investment" is health',
    analysis: [
      'MoneySense is clear for ages 19–29: build an emergency fund first, then put no more than 15% of income toward protection.',
      'The best "investment" now is to lock in health cover while young, at low rates — rather than rushing into savings or investment products.',
    ],
    quote: 'What he lacks isn’t returns — it’s the floor that keeps one accident from derailing a career that’s just begun.',
    solutionEyebrow: '03 / Solution · Three layers of basic cover',
    solutionTitle: 'Build the foundation on ≤8% of income',
    solutionLead: 'No savings or investment products — just the three most basic, best-value layers of protection.',
    meta: [
      { label: '① Hospital plan (IP) + rider', value: '~S$2***', sub: 'Follows him · for life' },
      { label: '② Personal accident', value: '~S$2**', sub: 'Excellent value' },
      { label: '③ Early-stage critical illness', value: '~S$2***', sub: 'Locks ~S$10**** of cover' },
      { label: 'Total annual premium', value: '< 8% of income', sub: 'Well within the 15% line' },
    ],
    table: {
      head: ['Dimension', 'Before', 'After'],
      rows: [
        ['Hospital', '✕', '✅ Hospital plan (IP) + rider'],
        ['Accident', '✕', '✅ Personal accident'],
        ['Critical illness', '✕', '✅ Early-stage CI (low rate locked)'],
        ['Life / TPD / LTC', '✕', '— added as life stages arrive'],
      ],
    },
    dataChips: [
      { label: 'Unprotected dimensions before', value: '5 / 6' },
      { label: 'Now secured', value: 'Hospital · Accident · CI' },
      { label: 'Premium as % of income', value: '< 8%' },
    ],
  },

  // 2. 30 new home
  {
    slug: 'new-home',
    age: 30,
    gender: 'female',
    mapLabel: 'Age 30 · Buying a home',
    stageIcon: 'home',
    theme: 'Protecting the home and each other',
    icon: 'home',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · Buying a home · Protecting home & each other',
    title: 'Just took on a mortgage — if I’m the one who falls, can we keep the home?',
    titleHi: 'can we keep the home?',
    lead: 'The foundation was laid back at 25, but buying a home raises the stakes — the gap is now in "family responsibility." She doesn’t need more insurance, just a precise hedge against the mortgage risk.',
    pills: ['PR + citizen household', 'Dual income', 'S$600k mortgage', 'Steady, conservative'],
    hexBefore: [3, 3, 2, 0, 0, 0],
    hexAfter: [3, 3, 3, 3, 1, 0],
    hexBeforeLabel: 'Before buying · three corners',
    hexAfterLabel: 'After · Life added',
    hexNote:
      'This stage adds the key piece — Life. A decreasing-term life policy precisely hedges that fixed, long-term mortgage debt; critical illness is topped up at the same time. TPD can ride on the life policy; long-term care waits for a later stage.',
    profile: [
      { icon: '🏠', title: 'Assets today', items: ['Just bought their own home', 'Mortgage ~S$60****', 'Stable dual-income cash flow; savings used on the down payment'] },
      { icon: '😟', title: 'Her worries', items: ['"If one of us loses our income,', 'can the other carry the whole mortgage?"'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Hospital ✓ · Accident ✓', 'Critical illness ◐ (low)', 'Life ✕'] },
      { icon: '🎯', title: 'Core needs', items: ['If one dies / falls ill, the mortgage won’t crush the other', 'Close the critical-illness gap'] },
    ],
    analysisTitle: 'The biggest exposure is that mortgage',
    analysis: [
      'MoneySense rule of thumb: death / TPD cover ~9× annual income, critical illness ~4× annual income.',
      'Their biggest exposure is the mortgage — a fixed, long-term debt best hedged precisely with decreasing-term life. Total premiums still stay within 15% of household income.',
    ],
    quote: 'She doesn’t want more insurance — she wants the home to stay safe, no matter what.',
    solutionEyebrow: '03 / Solution · Hedge the mortgage + top up CI',
    solutionTitle: 'Pin the mortgage risk down with decreasing-term life',
    solutionLead: 'Cover decreases with the mortgage, matching the outstanding balance; critical illness is topped up to replace income during illness.',
    meta: [
      { label: 'Decreasing-term life (one each)', value: '~S$2***/person', sub: 'Payout clears the mortgage' },
      { label: 'CI top-up (each)', value: '+~S$20****', sub: 'Income replacement · recovery costs' },
      { label: 'Debt hedged', value: 'S$600k', sub: 'Full mortgage cover' },
    ],
    table: {
      head: ['Dimension', 'Before buying', 'After'],
      rows: [
        ['Critical illness', '◐ low', '✅ Topped up'],
        ['Life', '✕', '✅ Decreasing-term life'],
        ['TPD', '✕', '◐ Can add as a rider'],
      ],
    },
    dataChips: [
      { label: 'Debt hedged', value: 'Full S$600k mortgage' },
      { label: 'New dimension', value: 'Life' },
      { label: 'Premium as % of household income', value: '< 15%' },
    ],
  },

  // 3. 32 new parents
  {
    slug: 'new-parents',
    age: 32,
    gender: 'female',
    mapLabel: 'Age 32 · Children’s education',
    stageIcon: 'education',
    theme: 'Cover and a future for the child',
    icon: 'baby',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · New parents · Cover & education fund',
    title: 'Baby’s just arrived — where do cover and the education fund begin?',
    titleHi: 'where do cover and the education fund begin?',
    lead: 'Many new parents instinctively "insure the child first," but MoneySense puts the order differently — parents are the child’s biggest "policy." We shore up the parents first, then build the child’s foundation and start saving for the future.',
    pills: ['Newborn', 'Dual-income family', 'Parents first', 'Education fund started'],
    hexBefore: [3, 3, 3, 3, 1, 0],
    hexAfter: [3, 3, 3, 3, 3, 0],
    hexBeforeLabel: 'Before the baby',
    hexAfterLabel: 'After · TPD completed',
    hexNote:
      'A new baby raises family responsibility again, so the parents’ Life and TPD are topped up (TPD completed). The child gets their own "small hexagon": child hospital + child accident + (optional) child critical illness. The education fund starts as a "future cash flow" at the same time.',
    profile: [
      { icon: '👶', title: 'Family today', items: ['Baby just born', 'Spending pattern is shifting', 'Starting to worry about future education costs'] },
      { icon: '😟', title: 'Her worries', items: ['Wants the best for the child but unsure of the order', 'Worried the education fund won’t be enough when needed'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Parents: hospital / accident / CI in place ✓', 'Child: no policies yet ✕'] },
      { icon: '🎯', title: 'Core needs', items: ['Basic health cover for the baby', 'Long-term saving for education around age 18'] },
    ],
    analysisTitle: 'Parents first, then the child — don’t reverse the order',
    analysis: [
      'Newborn cover rewards starting early: the sooner it’s set up, the simpler the underwriting and the lower the rate.',
      'But order matters — parents first, child second. The parents’ income is the family’s cash-flow engine; the parents are the child’s biggest "policy."',
    ],
    quote: 'The child’s cover matters — but make sure the parents are solid first.',
    solutionEyebrow: '03 / Solution · Two steps',
    solutionTitle: 'Lay the baby’s foundation, then save for the future',
    solutionLead: 'Step one secures the baby’s basic health; step two builds long-term savings for education around age 18.',
    meta: [
      { label: '① Child hospital plan', value: '~S$2**', sub: 'Health foundation' },
      { label: '② Child accident', value: '~S$2**', sub: 'A must for active years' },
      { label: '③ (Optional) child CI', value: 'Locks S$10****', sub: 'Low lifetime rate' },
      { label: '④ Education savings', value: '~S$2***/yr', sub: 'Cash flow when it’s needed' },
    ],
    table: {
      head: ['Who', 'Dimension', 'After'],
      rows: [
        ['Parents', 'Life / TPD', '✅ Heavier duty · topped up'],
        ['Child', 'Hospital / Accident', '✅ Health foundation'],
        ['Child', 'CI (optional)', '◐ Lock rate early'],
        ['Future', 'Education fund', '✅ Long-term saving started'],
      ],
    },
    dataChips: [
      { label: 'Key reminder', value: 'Parents are the child’s biggest policy' },
      { label: 'Added for child', value: 'Hospital · Accident · (CI optional)' },
      { label: 'Education fund start', value: 'From birth' },
    ],
  },

  // 4. 35 wealth growth
  {
    slug: 'wealth-growth',
    age: 35,
    gender: 'female',
    mapLabel: 'Age 35 · Wealth growth',
    stageIcon: 'wealth',
    theme: 'Tax, growth, early retirement',
    icon: 'growth',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · Wealth growth · Tax & early retirement',
    title: 'Thinking at 35 about life at 50 — how to save tax, grow wealth, and retire early?',
    titleHi: 'save tax, grow wealth, and retire early?',
    lead: 'Her protection hexagon was completed long ago; now she wants to put the "pre-tax" part of a high income to work — first maxing SRS to cut tax, then using a "grow-first, dividends-later" pool to lay steady cash flow toward early retirement at 50.',
    pills: ['EP holder', 'Family-business heir', 'Target: retire at 50', 'Max SRS tax relief'],
    hexBefore: [3, 3, 3, 3, 3, 0],
    hexAfter: [3, 3, 3, 3, 3, 1],
    hexBeforeLabel: 'Protection layer full',
    hexAfterLabel: 'Into growth + retirement',
    hexNote:
      'The protection layer is already full, so this stage adds no more cover and shifts the focus to "growth + retirement." The assets move from "all protection" to "protection base + tax optimisation + retirement cash flow."',
    profile: [
      { icon: '💰', title: 'Assets today', items: ['High income, complete cover', 'Ongoing investable surplus', 'No systematic tax planning yet'] },
      { icon: '😟', title: 'Her worries', items: ['Tax burden is on the high side', 'Wants to retire at 50 but has no clear cash-flow path', 'Doesn’t want to watch the markets'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Hospital / accident / CI ✓', 'Life / TPD ✓', 'Protection layer full'] },
      { icon: '🎯', title: 'Core needs', items: ['Legal tax saving', 'Steady growth on spare cash', 'A supplementary cash flow for retiring at 50'] },
    ],
    analysisTitle: 'SRS: one of the few direct tax cuts for high-income EPs',
    analysis: [
      'For a high-income EP holder, SRS (Supplementary Retirement Scheme) is one of the few tools that directly reduces tax: foreigners can contribute up to S$35,700 a year, cutting that year’s taxable income.',
      'But SRS cash sitting idle does little — pair it with a "grow-first, dividends-later" strategy so the money compounds over the 15 years from 35 to 50, then converts into a dividend cash flow in retirement.',
    ],
    quote: 'The confidence to retire early comes from certain cash flow — not from betting on returns.',
    solutionEyebrow: '03 / Solution · Tax + growth + retirement, all three',
    solutionTitle: 'Set up at 35 → grow for 15 years → draw from 50',
    solutionLead: 'Use SRS to cut tax this year, a "grow-first, dividends-later" fund to compound long-term, and steady savings to supplement retirement cash flow.',
    meta: [
      { label: '① Max SRS', value: 'S$35,700/yr', sub: 'Directly offsets taxable income' },
      { label: '② Grow-then-dividend fund', value: '~S$****/yr', sub: 'Grow early · dividends later' },
      { label: '③ Steady savings plan', value: 'Draw from 50', sub: 'Supplements retirement cash flow' },
    ],
    table: {
      head: ['Stage', 'Action', 'Goal'],
      rows: [
        ['Age 35', 'Max SRS + set up fund', 'Cut tax now · start compounding'],
        ['35→50', 'Grow', 'Let the principal compound over 15 years'],
        ['From 50', 'Switch to dividends / draw', 'Supplementary cash flow for early retirement'],
      ],
    },
    dataChips: [
      { label: 'Annual tax relief', value: 'SRS S$35,700' },
      { label: 'Timeline', value: '35 → 50 (15 years)' },
      { label: 'Retirement strategy', value: 'Grow first, dividends later' },
    ],
  },

  // 5. 40 USD retirement
  {
    slug: 'usd-retirement',
    age: 40,
    gender: 'male',
    mapLabel: 'Age 40 · Retirement planning',
    stageIcon: 'retire',
    theme: 'Steady USD retirement cash flow',
    icon: 'stable',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · Retirement planning · USD savings plan',
    title: 'Solid income — how should retirement cash flow and USD savings be designed?',
    titleHi: 'retirement cash flow and USD savings be designed?',
    lead: 'He isn’t chasing returns — he wants a steady, flexible, inheritable home for some idle USD: certainty, plus the option to start early if his career rhythm changes.',
    pills: ['Senior executive', 'US$500k idle USD', 'Low risk', 'Flexible either way'],
    hexBefore: [3, 3, 3, 3, 3, 1],
    hexAfter: [3, 3, 3, 3, 3, 2],
    hexBeforeLabel: 'Fully protected',
    hexAfterLabel: 'Add retirement cash flow + early LTC',
    hexNote:
      'Protection is complete; this stage adds the early shape of "retirement cash flow" and "long-term care." The assets begin shifting from "protection + growth" toward "cash flow + legacy."',
    profile: [
      { icon: '💵', title: 'Assets today', items: ['Stable career, peak earnings', 'US$50**** of USD not needed short-term'] },
      { icon: '😟', title: 'His considerations', items: ['No appetite for short-term volatility', 'Worried there’s nothing ready to start if his career rhythm changes'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Group medical, basic hospital ✓', 'Some life / CI, basic accident ✓'] },
      { icon: '🎯', title: 'Core needs', items: ['Long-term steady cash flow', 'Steady + flexible', 'Considers family legacy too'] },
    ],
    analysisTitle: 'A flexible home for some idle USD',
    analysis: [
      'The need is clear: not chasing returns, but a steady home for idle USD — flexible either way, and inheritable.',
      'What fits him best is "flexible either way": start early if needed, keep compounding if not.',
    ],
    quote: 'He wants certainty — and the ease of money he can use anytime, and pass on if he doesn’t.',
    solutionEyebrow: '03 / Solution · USD savings plan (single premium)',
    solutionTitle: 'Pay once, draw at your own pace',
    solutionLead: 'A single premium; choose to draw annual cash flow from year 5 or year 15, covered to age 100, with any unused portion passed on.',
    meta: [
      { label: 'Single premium', value: 'US$50****', sub: 'Pay only once' },
      { label: 'Early draw (from yr 5)', value: '~US$2****/yr', sub: 'Can start early' },
      { label: 'Later draw (from yr 15)', value: '~US$4****/yr', sub: 'Compounds longer' },
      { label: 'Coverage', value: 'To age 100', sub: 'Unused keeps compounding · inheritable' },
    ],
    table: {
      head: ['Draw option', 'Start', 'Annual cash flow (illustrative)'],
      rows: [
        ['Early', 'From year 5', '~US$2****'],
        ['Later', 'From year 15', '~US$4****'],
      ],
    },
    dataChips: [
      { label: 'Funding', value: 'Single premium' },
      { label: 'Draw flexibility', value: 'Year 5 / 15 optional' },
      { label: 'Coverage', value: 'To age 100 + legacy' },
    ],
  },

  // 6. 45 business owner
  {
    slug: 'business-owner',
    age: 45,
    gender: 'male',
    mapLabel: 'Age 45 · Growing a business',
    stageIcon: 'business',
    theme: 'Offence and defence · a complete hexagon',
    icon: 'building',
    eyebrow: 'Client case · For illustration only',
    tag: 'CASE · Business owner · Growth / floor / legacy',
    title: 'Company and family money are mixed — how to grow, protect the floor, and pass it on?',
    titleHi: 'grow, protect the floor, and pass it on?',
    lead: 'As the founder of an AI startup, his risks differ from an ordinary executive’s — business swings, and blurred lines between personal and company assets. A combined approach fills in the hexagon’s last corner while arranging growth, a safety floor and legacy all at once.',
    pills: ['AI startup founder', 'Family + business duty', 'Asset segregation', 'High-leverage legacy'],
    hexBefore: [3, 3, 3, 3, 3, 2],
    hexAfter: [3, 3, 3, 3, 3, 3],
    hexBeforeLabel: 'Almost complete',
    hexAfterLabel: 'Hexagon fully closed ⭐',
    hexNote:
      'From a single corner at 25 to here at 45, the hexagon closes completely: long-term care is filled in, Life is boosted with high leverage via IUL, and a layer of business asset segregation and legacy is added on top.',
    profile: [
      { icon: '🏢', title: 'Assets today', items: ['Runs an AI startup, with meaningful savings', 'Blurred line between personal and company assets'] },
      { icon: '😟', title: 'His considerations', items: ['Business swings — fears "company trouble dragging in the family"', 'Wants to leave the family a certain sum'] },
      { icon: '🛡️', title: 'Existing cover', items: ['Health cover complete (hospital / CI / accident) ✓', 'Some life cover, but a gap remains against the dual duty'] },
      { icon: '🎯', title: 'Core needs', items: ['Part of the money to outpace inflation long-term', 'Part as a high-leverage death-benefit floor', 'Asset segregation + legacy'] },
    ],
    analysisTitle: 'Why a "combination," not a single product',
    analysis: [
      'A participating fund provides "steadiness," and IUL provides "protection + flexible growth" — exactly matching his "offence and defence" needs.',
      'Unique to owners: use a policy structure to segregate and pass on personal vs. company assets — so business swings don’t breach the family’s floor.',
    ],
    quote: 'Keep the company’s swings from breaching the family’s floor.',
    solutionEyebrow: '03 / Solution · A combination',
    solutionTitle: 'Steady base + high-leverage floor + asset segregation',
    solutionLead: 'A participating fund as a steady base, IUL to leverage a high death benefit, plus an owner-specific asset-segregation and legacy arrangement.',
    meta: [
      { label: '① Participating fund / savings', value: '~S$2***/yr', sub: 'Steady-growth base' },
      { label: '② Indexed universal life (IUL)', value: '~US$1***** cover', sub: 'High leverage + cash-value growth' },
      { label: '③ Asset segregation / legacy', value: 'Owner-specific', sub: 'Personal vs. company line' },
    ],
    table: {
      head: ['Tool', 'Role', 'Notes'],
      rows: [
        ['Participating fund', 'Steady base', 'Smoothed growth · for mid/long-term money'],
        ['IUL', 'Protection + flexible growth', 'Leverages ~US$1***** cover · cash value with a floor'],
        ['Asset segregation', 'Owner-specific', 'Clear lines · a certain sum set aside for family'],
      ],
    },
    dataChips: [
      { label: 'Death-benefit leverage', value: '~US$1***** cover' },
      { label: 'Protection hexagon', value: 'Fully closed' },
      { label: 'Return nature', value: 'Dividends & cash value non-guaranteed · per policy' },
    ],
  },
];
